name: test
run-name: testing 
on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Prepare Test Environment
      run: |
        cd marketing
        mkdir -p ignore_test_file
        mv src/test/java/comm-terminal-sales/*.java ignore_test_file/ || true
        mv ignore_test_file/스펙재방문시타켓팅수치증가Test.java src/test/java/comm-terminal-sales/ || true
    - name: Compile and Run Specific Test
      run: |
        cd marketing
        mvn test-compile
        mvn test -Dtest=comm-terminal-sales.스펙재방문시타켓팅수치증가Test -Dsurefire.useFile=false
    - name: Restore Test Files
      if: always()
      run: |
        cd marketing
        if [ -d "ignore_test_file" ] && [ "$(ls -A ignore_test_file)" ]; then
          mv ignore_test_file/*.java src/test/java/comm-terminal-sales/
        fi
        rm -rf ignore_test_file
    - name: Print Test Results
      if: always()
      run: |
        cd marketing
        cat target/surefire-reports/*.txt || true